sudo: required
dist: trusty

os: linux

language: c

compiler:
  - clang

env:
  global:
    - PREFIX="${HOME}/opt"
    - OPENSSL_VERSION="1.0.2l"

addons:
  apt:
    packages:
      - libpam0g-dev
      - linux-libc-dev
      - man2html

script:
  - wget https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz
  - tar zxf openssl-${OPENSSL_VERSION}.tar.gz
  - cd openssl-${OPENSSL_VERSION}
  - ./config shared --prefix="${PREFIX}" --openssldir="${PREFIX}" -DPURIFY
  - make all install_sw
  - cd ..
  - export CFLAGS="-ggdb -fsanitize=memory -fPIE -pie -fno-omit-frame-pointer" LDFLAGS="-fsanitize=memory -fPIE -pie -fno-omit-frame-pointer"
  - clang -I${PREFIX}/include -L${PREFIX}/lib -lssl -lcrypto test.c
  - ./a.out

